# Generated by Django 4.2 on 2023-12-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherschedule',
            options={'ordering': ('group', 'teacher_name'), 'verbose_name': 'Teacher Schedule', 'verbose_name_plural': 'Teacher Schedules'},
        ),
    ]
